pipeline {
    agent any

    environment {
        AWS_REGION = 'ap-south-1'

        FRONTEND_REPO = '225989367272.dkr.ecr.ap-south-1.amazonaws.com/project-18-frontend'
        BACKEND_REPO  = '225989367272.dkr.ecr.ap-south-1.amazonaws.com/project-18-backend'
    }

    stages {

        stage('Build Frontend Image') {
            steps {
                dir('project-18-jenkins-eks-cicd-pipeline/frontend') {
                    sh '''
                    docker build -t $FRONTEND_REPO:latest .
                    '''
                }
            }
        }

        stage('Build Backend Image') {
            steps {
                dir('project-18-jenkins-eks-cicd-pipeline/backend') {
                    sh '''
                    docker build -t $BACKEND_REPO:latest .
                    '''
                }
            }
        }

        stage('Login To ECR') {
            steps {
                sh '''
                aws ecr get-login-password --region $AWS_REGION \
                | docker login \
                --username AWS \
                --password-stdin 225989367272.dkr.ecr.ap-south-1.amazonaws.com
                '''
            }
        }

        stage('Push Frontend') {
            steps {
                sh '''
                docker push $FRONTEND_REPO:latest
                '''
            }
        }

        stage('Push Backend') {
            steps {
                sh '''
                docker push $BACKEND_REPO:latest
                '''
            }
        }

        stage('Deploy To EKS') {
            steps {
                sh '''
                aws eks update-kubeconfig \
                --region ap-south-1 \
                --name project-18-eks-cluster

                kubectl rollout restart deployment/frontend
                kubectl rollout restart deployment/backend
                '''
            }
        }

        stage('Verify Deployment') {
            steps {
                sh '''
                kubectl get pods
                '''
            }
        }
    }
}