pipeline {
    agent any

    stages {

        stage('Verify Docker') {
            steps {
                sh 'docker --version'
            }
        }

        stage('Verify AWS') {
            steps {
                sh 'aws sts get-caller-identity'
            }
        }

        stage('Verify EKS') {
            steps {
                sh '''
                aws eks update-kubeconfig \
                --region ap-south-1 \
                --name project-18-eks-cluster

                kubectl get nodes
                '''
            }
        }
    }
}