apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend
        # image: 225989367272.dkr.ecr.ap-south-1.amazonaws.com/project-18-backend:v1 -- harcoded
        image: 225989367272.dkr.ecr.ap-south-1.amazonaws.com/project-18-backend:latest

        ports:
        - containerPort: 8080